-- 013_admin.sql (Postgres)
-- Adds is_admin flag to users and creates the admin_audit_log table.

ALTER TABLE users ADD COLUMN IF NOT EXISTS is_admin BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS admin_audit_log (
  id             INT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id  TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  action         TEXT NOT NULL,
  target_type    TEXT DEFAULT NULL,
  target_id      TEXT DEFAULT NULL,
  payload_json   TEXT DEFAULT NULL,
  created_at     TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_log_actor   ON admin_audit_log(actor_user_id);
CREATE INDEX IF NOT EXISTS idx_admin_audit_log_created ON admin_audit_log(created_at);
