-- 016_organizations.sql (Postgres)
-- Introduces the org model: organizations, memberships, businesses, and invite
-- tokens. Each existing user receives a personal org (id == user_id for easy
-- backfilling in 017), an owner membership, and a "Personal" business.

-- ── 1. New tables ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS organizations (
  id         TEXT PRIMARY KEY,
  name       TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS org_memberships (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id     TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id    TEXT NOT NULL REFERENCES users(id)         ON DELETE CASCADE,
  role       TEXT NOT NULL DEFAULT 'member'
               CHECK (role IN ('owner', 'member')),
  created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(org_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_org_memberships_user ON org_memberships(user_id);
CREATE INDEX IF NOT EXISTS idx_org_memberships_org  ON org_memberships(org_id);

CREATE TABLE IF NOT EXISTS businesses (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id     TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_businesses_org ON businesses(org_id);

CREATE TABLE IF NOT EXISTS org_invites (
  id         TEXT PRIMARY KEY,
  org_id     TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  invited_by TEXT NOT NULL REFERENCES users(id)         ON DELETE CASCADE,
  email      TEXT NOT NULL,
  role       TEXT NOT NULL DEFAULT 'member'
               CHECK (role IN ('owner', 'member')),
  status     TEXT NOT NULL DEFAULT 'pending'
               CHECK (status IN ('pending', 'accepted', 'expired')),
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_org_invites_org   ON org_invites(org_id);
CREATE INDEX IF NOT EXISTS idx_org_invites_email ON org_invites(email);

-- ── 2. Seed personal orgs for all existing users ──────────────────────────────

INSERT INTO organizations(id, name)
SELECT id, COALESCE(name, COALESCE(email, 'My Organization'))
FROM users
ON CONFLICT (id) DO NOTHING;

INSERT INTO org_memberships(org_id, user_id, role)
SELECT id, id, 'owner'
FROM users
ON CONFLICT (org_id, user_id) DO NOTHING;

INSERT INTO businesses(org_id, name)
SELECT id, 'Personal'
FROM users
WHERE NOT EXISTS (
  SELECT 1 FROM businesses b WHERE b.org_id = users.id AND b.name = 'Personal'
);
